stages:
 - test

image: python:3.8

before_script: 
  - pip3 install -r requirements.txt
  - cd app/
  - python3 manage.py makemigrations simpleapp 

test:
    stage: test
    script: 
     - coverage run --rcfile=../.coveragerc --source='.' manage.py test

